# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VacinasARS
                                 A QGIS plugin
 Este plugin permite a visualização temporal da vacinação por aRS em Portugal continental.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-21
        copyright            : (C) 2021 by Eduarda Ribeiro, Carla Rodrigues
        email                : eduardalopesribeiro@outlook.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VacinasARS class from file VacinasARS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vacinas_ars import VacinasARS
    return VacinasARS(iface)
